# Dockerfile.api
FROM node:20-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

COPY api/package*.json ./
RUN pnpm install --frozen-lockfile

COPY api .
RUN pnpm run build

CMD ["pnpm", "start"]
