version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bluesky_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cron:
    image: alpine
    environment:
      CRON_SECRET: ${CRON_SECRET:-your-secret-here}
    command: >
      /bin/sh -c "
      apk add --no-cache curl &&
      while true; do
        echo 'Making cron request...' &&
        curl -v -X POST -H \"Authorization: Bearer \$CRON_SECRET\" http://host.docker.internal:3000/api/cron/check-posts &&
        echo 'Sleeping for 60 seconds...' &&
        sleep 60;
      done
      "

volumes:
  postgres_data:
